route:
    receiver: "slack"

receivers:
    - name: "slack"
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: "Prometheus"
            channel: <YOUR_CHANNEL_NAME>
            api_url: <YOUR_WEBHOOK_URL>
