name: "monitoring"

networks:
    monitor-net:
        driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
    prometheus:
        image: prom/prometheus:v2.41.0
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/config.yml"
            - "--web.enable-lifecycle"
        restart: unless-stopped
        ports:
            - 9090:9090
        networks:
            - monitor-net
        labels:
            org.label-schema.group: "monitoring"

    grafana:
        image: grafana/grafana:9.3.2
        container_name: grafana
        volumes:
            - grafana_data:/var/lib/grafana
            # - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        environment:
            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
            - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        ports:
            - 3000:3000
        networks:
            - monitor-net
        labels:
            org.label-schema.group: "monitoring"

    alertmanager:
        image: prom/alertmanager:v0.25.0
        container_name: alertmanager
        volumes:
            - ./alertmanager:/etc/alertmanager
        command:
            - "--config.file=/etc/alertmanager/config.yml"
            - "--storage.path=/alertmanager"
        restart: unless-stopped
        ports:
            - 9093:9093
        networks:
            - monitor-net
        labels:
            org.label-schema.group: "monitoring"
