name: "CI/CD"

networks:
    cicd-net:
        driver: bridge

services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        volumes:
            - ~/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
        restart: unless-stopped
        ports:
            - 9000:8080
        networks:
            - cicd-net
        labels:
            org.label-schema.group: "CI/CD"
