pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the application artifact..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying to artifactory..'
            }
        }
    }
}