global:
    scrape_interval: 30s
    scrape_timeout: 25s

rule_files:
    - alert.yml

scrape_configs:
    - job_name: "prometheus"
      scrape_interval: 20s
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "nodeexporter"
      scrape_interval: 20s
      static_configs:
          - targets: ["nodeexporter:9100"]

    - job_name: "cadvisor"
      scrape_interval: 20s
      static_configs:
          - targets: ["cadvisor:8080"]

alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets:
                    - "alertmanager:9093"
